# Generated by Django 5.1.5 on 2025-01-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_news_alter_buyer_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('rarity', models.CharField(choices=[('common', 'Обычное'), ('rare', 'Редкое'), ('ultra_rare', 'Сверхредкое'), ('mythical', 'Мифическое'), ('legendary', 'Легендарное'), ('secret', 'Секретное')], default='common', max_length=20, verbose_name='Редкость')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Размер')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('age_limited', models.BooleanField(default=False, verbose_name='Возрастное ограничение')),
                ('buyer', models.ManyToManyField(related_name='achievements', to='task1.buyer', verbose_name='Покупатели')),
            ],
        ),
    ]
