# Generated by Django 5.1.5 on 2025-01-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='age_limited',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='size',
        ),
    ]
